name: sandbox-transformers
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pip
  - pip:
    - transformers
    - pillow
    - timm
    - gradio
    - scipy
