name: sandbox-transformers
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Matches your CUDA version
  - transformers
  - timm
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel