name: sandbox-transformers
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pillow
  - torchvision
  - torchaudio
  - pytorch             # Will be installed from the pytorch channel
  - pytorch-cuda=11.8   # Provides the matching CUDA runtime
  - transformers[sentencepiece]
  - accelerate
  - evaluate
  - timm
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - graphviz
  - pip
  - pip:
      - python-dotenv
      - matplotlib
      - graphviz
